In [4]:
import pandas as pd

data = pd.read_csv("Activities.csv")

display(data)

,Activity Type,Date,Favorite,Title,Distance,Calories,Time,Avg HR,Max HR,Aerobic TE,...,Avg Power,Max Power,Steps,Decompression,Best Lap Time,Number of Laps,Moving Time,Elapsed Time,Min Elevation,Max Elevation
0,Running,2025-09-28 23:07:55,False,Fullerton Running,8.56,"1,035",01:14:14,141,150,3.1,...,358,577,"11,904",No,00:04:45.9,9,01:14:10,01:16:04,207,249
1,Running,2025-09-27 10:21:20,False,Fullerton Running,16.01,"1,944",02:10:28,153,177,4.1,...,382,494,"21,386",No,00:00:03.1,17,02:10:19,02:13:38,209,287
2,Treadmill Running,2025-09-26 09:25:42,False,Treadmill Running,5.00,539,00:52:20,129,140,2.0,...,285,347,"8,338",No,00:08:58.6,5,00:52:04,00:54:37,--,--
3,Running,2025-09-25 11:48:47,False,Fullerton Running,8.01,887,01:01:50,144,178,3.2,...,403,487,"10,314",No,00:00:02.5,9,01:01:42,01:03:08,207,245
4,Treadmill Running,2025-09-24 12:54:49,False,Treadmill Running,7.00,727,01:14:28,127,151,2.1,...,257,318,"11,922",No,00:02:58.8,7,01:13:43,01:16:52,--,--
5,Running,2025-09-23 19:53:50,False,Fullerton Running,8.56,"1,033",01:04:12,161,183,4.0,...,413,625,"10,686",No,00:00:02.6,17,01:04:08,01:06:11,191,250
6,Running,2025-09-22 21:19:42,False,Fullerton Running,7.02,862,00:57:43,150,165,3.2,...,377,557,"9,438",No,00:00:04.4,8,00:57:40,00:57:48,210,260
7,Running,2025-09-20 19:18:33,False,Fullerton Running,20.03,"2,482",02:55:27,152,174,4.3,...,359,526,"28,328",No,00:00:09.9,21,02:55:15,02:57:27,209,255
8,Treadmill Running,2025-09-19 18:36:07,False,Treadmill Running,4.00,430,00:49:56,120,129,1.3,...,280,311,"7,676",No,00:06:10.7,5,00:49:02,00:51:45,--,--
9,Running,2025-09-18 21:36:23,False,Fullerton Running,5.06,631,00:44:22,145,160,2.8,...,353,510,"7,172",No,00:00:22.6,6,00:44:16,00:44:58,212,255
10,Running,2025-09-17 17:41:47,False,Fullerton Running,6.10,735,00:50:43,147,191,3.4,...,366,602,"7,324",No,00:00:01.7,15,00:43:36,00:52:19,182,228
11,Running,2025-09-16 17:39:32,False,Fullerton Running,5.01,592,00:32:56,174,190,4.0,...,482,549,"5,690",No,00:00:02.4,6,00:32:54,00:32:56,204,228
12,Treadmill Running,2025-09-15 16:32:41,False,Treadmill Running,5.00,575,00:50:36,134,153,2.2,...,365,485,"8,046",No,00:00:48.2,7,00:49:56,00:51:50,--,--
13,Running,2025-09-14 11:17:28,False,Fullerton Running,13.15,"1,629",01:44:43,161,181,4.7,...,389,480,"17,412",No,00:01:18.4,14,01:44:31,01:48:20,224,288
14,Running,2025-09-13 19:23:52,False,Fullerton Running,7.01,840,00:51:23,161,186,3.9,...,421,573,"8,598",No,00:00:03.6,8,00:51:17,00:52:05,196,255
15,Treadmill Running,2025-09-12 19:25:24,False,Treadmill Running,10.00,978,01:26:10,142,175,3.2,...,336,525,"13,426",No,00:05:08.4,10,01:22:50,01:36:51,--,--
16,Running,2025-09-10 20:17:49,False,Fullerton Running,10.00,"1,270",01:32:52,147,162,3.3,...,332,406,"14,882",No,00:00:02.9,11,01:32:44,01:34:10,220,259
17,Running,2025-09-09 20:26:04,False,Fullerton Running,10.01,"1,233",01:13:22,167,179,4.4,...,426,677,"12,302",No,00:00:04.9,11,01:13:19,01:14:43,227,270
18,Running,2025-09-07 20:14:34,False,Fullerton Running,17.18,"2,076",02:26:33,150,175,3.9,...,363,449,"23,660",No,00:01:27.5,18,02:26:22,02:29:22,218,257
19,Treadmill Running,2025-09-06 21:47:21,False,Treadmill Running,4.00,435,00:36:30,139,178,2.3,...,275,452,"4,898",No,00:04:15.6,4,00:29:08,00:38:23,--,--

In [5]:
data.columns.to_list()
#Shows all the columns

['Activity Type',
 'Date',
 'Favorite',
 'Title',
 'Distance',
 'Calories',
 'Time',
 'Avg HR',
 'Max HR',
 'Aerobic TE',
 'Avg Run Cadence',
 'Max Run Cadence',
 'Avg Pace',
 'Best Pace',
 'Total Ascent',
 'Total Descent',
 'Avg Stride Length',
 'Avg Vertical Ratio',
 'Avg Vertical Oscillation',
 'Avg Ground Contact Time',
 'Avg GAP',
 'Normalized Power® (NP®)',
 'Training Stress Score®',
 'Avg Power',
 'Max Power',
 'Steps',
 'Decompression',
 'Best Lap Time',
 'Number of Laps',
 'Moving Time',
 'Elapsed Time',
 'Min Elevation',
 'Max Elevation']

In [9]:
data.iloc[: , 10:20]
# :->all rows, 10:20 columns 10 through 20
# [row selection, column selection]

,Avg Run Cadence,Max Run Cadence,Avg Pace,Best Pace,Total Ascent,Total Descent,Avg Stride Length,Avg Vertical Ratio,Avg Vertical Oscillation,Avg Ground Contact Time
0,160,176,8:40,5:45,26,46,1.16,8.4,9.7,279
1,164,215,8:09,6:36,230,203,1.20,8.1,9.6,267
2,159,165,10:28,9:02,--,--,0.95,9.3,8.8,295
3,166,176,7:43,6:48,98,79,1.25,7.8,9.6,259
4,160,169,10:38,9:57,--,--,0.85,9.6,8.2,295
5,167,183,7:30,5:21,39,66,1.28,7.7,9.7,256
6,164,179,8:14,5:47,92,105,1.19,8.1,9.6,269
7,162,177,8:46,6:28,266,285,1.14,8.4,9.5,277
8,154,161,12:29,9:59,--,--,0.97,9.3,8.9,299
9,162,170,8:46,6:49,56,69,1.13,8.4,9.5,276
10,144,218,8:19,5:31,92,115,1.32,7.4,9.5,246
11,173,177,6:35,6:12,56,75,1.41,6.9,9.8,235
12,159,167,10:07,6:42,--,--,1.22,8.0,9.8,270
13,166,235,7:58,6:48,108,82,1.21,7.9,9.5,261
14,167,179,7:20,5:48,75,102,1.31,7.5,9.8,253
15,155,174,8:37,6:02,--,--,1.18,8.1,9.4,272
16,160,167,9:17,7:51,43,56,1.08,8.7,9.4,284
17,168,215,7:20,5:05,125,121,1.31,7.5,9.8,252
18,162,175,8:32,6:57,217,220,1.17,8.3,9.6,275
19,134,225,9:08,6:49,--,--,1.18,7.6,8.4,251

In [10]:
data["Avg HR"].mean()

np.float64(147.2)

In [11]:
data["Distance"].mean()

np.float64(8.8355)

In [6]:
data["Distance"]

0      8.56
1     16.01
2      5.00
3      8.01
4      7.00
5      8.56
6      7.02
7     20.03
8      4.00
9      5.06
10     6.10
11     5.01
12     5.00
13    13.15
14     7.01
15    10.00
16    10.00
17    10.01
18    17.18
19     4.00
Name: Distance, dtype: float64

In [13]:
simple_data = data[["Date", "Distance", "Avg HR", "Calories", "Time", "Steps", "Max HR"]]

In [14]:
display(simple_data)

                   Date  Distance  Avg HR Calories      Time   Steps  Max HR
0   2025-09-28 23:07:55      8.56     141    1,035  01:14:14  11,904     150
1   2025-09-27 10:21:20     16.01     153    1,944  02:10:28  21,386     177
2   2025-09-26 09:25:42      5.00     129      539  00:52:20   8,338     140
3   2025-09-25 11:48:47      8.01     144      887  01:01:50  10,314     178
4   2025-09-24 12:54:49      7.00     127      727  01:14:28  11,922     151
5   2025-09-23 19:53:50      8.56     161    1,033  01:04:12  10,686     183
6   2025-09-22 21:19:42      7.02     150      862  00:57:43   9,438     165
7   2025-09-20 19:18:33     20.03     152    2,482  02:55:27  28,328     174
8   2025-09-19 18:36:07      4.00     120      430  00:49:56   7,676     129
9   2025-09-18 21:36:23      5.06     145      631  00:44:22   7,172     160
10  2025-09-17 17:41:47      6.10     147      735  00:50:43   7,324     191
11  2025-09-16 17:39:32      5.01     174      592  00:32:56   5,690     190
12  2025-09-15 16:32:41      5.00     134      575  00:50:36   8,046     153
13  2025-09-14 11:17:28     13.15     161    1,629  01:44:43  17,412     181
14  2025-09-13 19:23:52      7.01     161      840  00:51:23   8,598     186
15  2025-09-12 19:25:24     10.00     142      978  01:26:10  13,426     175
16  2025-09-10 20:17:49     10.00     147    1,270  01:32:52  14,882     162
17  2025-09-09 20:26:04     10.01     167    1,233  01:13:22  12,302     179
18  2025-09-07 20:14:34     17.18     150    2,076  02:26:33  23,660     175
19  2025-09-06 21:47:21      4.00     139      435  00:36:30   4,898     178

In [25]:
display(simple_data["Steps"].sum())

np.int64(243402)

In [27]:
# 1. Calories & Distance

# Select only the Date, Distance, and Calories columns.

# Find the average calories burned per run.

# Identify the longest run (by distance) and how many calories it burned.

cals_distance_data = data[["Date", "Distance", "Calories"]]

                   Date  Distance Calories
0   2025-09-28 23:07:55      8.56    1,035
1   2025-09-27 10:21:20     16.01    1,944
2   2025-09-26 09:25:42      5.00      539
3   2025-09-25 11:48:47      8.01      887
4   2025-09-24 12:54:49      7.00      727
5   2025-09-23 19:53:50      8.56    1,033
6   2025-09-22 21:19:42      7.02      862
7   2025-09-20 19:18:33     20.03    2,482
8   2025-09-19 18:36:07      4.00      430
9   2025-09-18 21:36:23      5.06      631
10  2025-09-17 17:41:47      6.10      735
11  2025-09-16 17:39:32      5.01      592
12  2025-09-15 16:32:41      5.00      575
13  2025-09-14 11:17:28     13.15    1,629
14  2025-09-13 19:23:52      7.01      840
15  2025-09-12 19:25:24     10.00      978
16  2025-09-10 20:17:49     10.00    1,270
17  2025-09-09 20:26:04     10.01    1,233
18  2025-09-07 20:14:34     17.18    2,076
19  2025-09-06 21:47:21      4.00      435

In [32]:
cals_distance_data = data[["Date","Distance","Calories"]].copy()

cals_distance_data["Calories"] = (
    cals_distance_data["Calories"].str.replace(",", "").astype(int)
)

cals_distance_data["Calories"].mean()

np.float64(1046.65)

In [35]:
cals_distance_data.nlargest(1, "Distance")

                  Date  Distance  Calories
7  2025-09-20 19:18:33     20.03      2482

In [41]:
avg_hr = data["Avg HR"].mean()
avg_power = data["Avg Power"].mean()
total_steps = data["Steps"].sum()

step_conversion_data = data[[]]
print(avg_hr, avg_power, total_steps)

147.2 361.1 11,90421,3868,33810,31411,92210,6869,43828,3287,6767,1727,3245,6908,04617,4128,59813,42614,88212,30223,6604,898

In [42]:
#Changing the data into nums
data.columns.to_list()

['Activity Type',
 'Date',
 'Favorite',
 'Title',
 'Distance',
 'Calories',
 'Time',
 'Avg HR',
 'Max HR',
 'Aerobic TE',
 'Avg Run Cadence',
 'Max Run Cadence',
 'Avg Pace',
 'Best Pace',
 'Total Ascent',
 'Total Descent',
 'Avg Stride Length',
 'Avg Vertical Ratio',
 'Avg Vertical Oscillation',
 'Avg Ground Contact Time',
 'Avg GAP',
 'Normalized Power® (NP®)',
 'Training Stress Score®',
 'Avg Power',
 'Max Power',
 'Steps',
 'Decompression',
 'Best Lap Time',
 'Number of Laps',
 'Moving Time',
 'Elapsed Time',
 'Min Elevation',
 'Max Elevation']

In [49]:

data["Calories"].sum()

np.int64(20933)

In [50]:
#python function to change time into minutes

data["Time"] = pd.to_timedelta(data["Time"]).dt.total_seconds() / 60

data["Time"].mean()

np.float64(75.53999999999999)

In [ ]:
#Deleteing columns
data = data[["Date", "Distance", "Calories"]]